coffee_shop:
  outputs:
    dev:
      dataset: dbt_sam
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: aec-students
      threads: 8
      type: bigquery
  target: dev